version: 0.2

phases:
  install:
    runtime-versions:
      go: 1.18
    commands:
      - echo "Installing dependencies..."
      - cd tests && go mod tidy
      - cd ../evaluation && go mod tidy

  pre_build:
    commands:
      - echo "Preparing test environment..."
      - cd tests
      - cp ../repository_after/main.go .

  build:
    commands:
      - echo "Running tests..."
      - cd tests
      - go test -v .

  post_build:
    commands:
      - echo "Running evaluation..."
      - cd evaluation
      - go run evaluate.go

artifacts:
  files:
    - evaluation/reports/report.json

